name: CI - Math Operations
run-name: ${{ github.actor }} is running the CI for Math Operations ğŸš€

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ğŸ—ï¸ Build and Test on Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: ğŸ“¥ Check out repository code
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¦ Install dependencies
        run: npm install
        
      - name: ğŸ“¦ Install dependencies
        run: npm install --save-dev jest
      

      - name: ğŸ§ª Run tests
        run: npm test

      - name: ğŸ“‚ List project files
        run: ls -la

      - name: âœ… Job finished
        run: echo "ğŸ This job's status is ${{ job.status }}."
